title: "Jean Cedric Batac"
email: jcbatac2@cougarnet.uh.edu
description: "Computer Science student at the University of Houston"
url: https://jean-batac.github.io

author:
  name: "Jean Cedric Batac"
  avatar: "/images/profile.jpg"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-THDS66C4P2"
